Welcome msg for build19 clients
widelands/widelands_metaserver pull request #36
Opened 2018-08-20 19:10 UTC by Notabilis

Displaying a welcome message for build19 clients. Previously this has been done as the MotD message but that had problems with newer clients. Old clients now receive the hardcoded message, newer clients generate the message locally.

Also, removing chat message sanitizing. For once, the clients have to do this anyway ("never trust the network"). Also, it created bugs for both client versions due to doubled sanitizing.

2018-08-22 13:06 UTC, gunchleoc requested changes
Looks good to me - could you please change the strings and links to be identical to the ones in https://code.launchpad.net/~widelands-dev/widelands/bug-1784200-single-line-escaping/+merge/353446?

2018-08-23 22:11 UTC, Notabilis commented
Thanks for the review. The strings should now be the same.

2018-08-24 12:35 UTC, gunchleoc approved these changes

2018-08-24 12:35 UTC, gunchleoc commented
All good to go :)

2018-08-24 15:41 UTC, merged

2018-08-24 15:41 UTC, Notabilis commented
Thanks, I will deploy this shortly.